[package]
name = "file-mang-snbx"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
regex = "1"
ratatui = "0.30.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
